api/urls.py
from django.urls import path
from .views import DirectorListCreateView, DirectorRetrieveUpdateDestroyView, api_overview
from .views import ActorListCreateView, ActorRetrieveUpdateDestroyView
from .views import FilmListCreateView, MovieRetrieveUpdateDestroyView

urlpatterns = [
    path('', api_overview, name='api-overview'),

    path('directors/', DirectorListCreateView.as_view(), name='director-list-create'),
    path('directors/<int:pk>/', DirectorRetrieveUpdateDestroyView.as_view(), name='director-detail'),

    path('actors/', ActorListCreateView.as_view(), name='actor-list-create'),
    path('actors/<int:pk>/', ActorRetrieveUpdateDestroyView.as_view(), name='actor-detail'),

    path('film/', FilmListCreateView.as_view(), name='film-list-create'),
    path('film/<int:pk>/', MovieRetrieveUpdateDestroyView.as_view(), name='film-detail'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('api-auth/', include('rest_framework.urls')),
                  path("__debug__/", include("debug_toolbar.urls")),
                  path('', include('film.urls')),
                  path('api/', include('api.urls')),

              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

film/modules/actors/urls.py
from django.urls import path
from film.modules.actors.views import ActorCreateView, actor_delete, ActorListView, ActorUpdateView

app_name = 'actors'

urlpatterns = [
    path('actors/', ActorListView.as_view(), name='actors-list'),
    path('add-actor/', ActorCreateView.as_view(), name='add-actor'),
    path('delete-actor/<int:pk>', actor_delete, name='delete-actor'),
    path('update-actor/<int:pk>', ActorUpdateView.as_view(), name='update-actor')
]

film/urls.py
from django.urls import path, include
from film.views import FilmListView, FilmCreateView, FilmEditView, film_delete

app_name = 'film'

urlpatterns = [
    path('', FilmListView.as_view(), name='list_view'),
    path('create-film/', FilmCreateView.as_view(), name='create_view'),
    path('edit-film/<int:pk>/', FilmEditView.as_view(), name='edit_view'),
    path('delete-film/<int:pk>/', film_delete, name='delete_view'),

    path('', include('film.modules.actors.urls')),
    path('', include('film.modules.director.urls')),

]

film/models.py
from django.db import models


class Director(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ('name',)


class Actor(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ('name',)


class Movie(models.Model):
    title = models.CharField(max_length=100)
    year = models.IntegerField()
    director = models.ForeignKey(Director, on_delete=models.CASCADE)
    actors = models.ManyToManyField(Actor)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ('-year',)

film/modules/actors/views.py
from django.contrib import messages
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse
from django.views.generic import CreateView, UpdateView
from django_filters.views import FilterView
from film.filters import ActorFilter
from film.models import Actor


class ActorListView(FilterView):
    filterset_class = ActorFilter
    queryset = Actor.objects.all()
    template_name = 'actor/actors_list.html'
    context_object_name = 'actors'
    paginate_by = 25


class ActorCreateView(CreateView):
    model = Actor
    template_name = 'actor/create_actor.html'
    fields = '__all__'

    def get_success_url(self):
        return reverse('film:actors:actors-list')


class ActorUpdateView(UpdateView):
    pk_url_kwarg = 'pk'
    model = Actor
    template_name = 'actor/update_actor.html'
    fields = '__all__'

    def get_success_url(self):
        return reverse('film:actors:actors-list')


def actor_delete(request, pk):
    try:
        actor = get_object_or_404(Actor, pk=pk)
        actor.delete()
        messages.success(request, f'Successfully deleted actor {actor}')
        return redirect('film:actors:actors-list')
    except Exception as e:
        messages.error(request, f'Error to delete actor {e}')
        return redirect('film:actors:actors-list')

film/modules/director/views.py
from django.contrib import messages
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse
from django.views.generic import UpdateView, CreateView
from django_filters.views import FilterView
from film.filters import DirectorFilter
from film.models import Director


class DirectorListView(FilterView):
    model = Director
    template_name = 'director/director_list.html'
    filterset_class = DirectorFilter
    queryset = Director.objects.all()
    context_object_name = 'directors'
    paginate_by = 25


class DirectorUpdateView(UpdateView):
    model = Director
    template_name = 'director/update_director.html'
    pk_url_kwarg = 'pk'
    fields = '__all__'

    def get_success_url(self):
        return reverse('film:director:director-list')


class DirectorCreateView(CreateView):
    model = Director
    fields = '__all__'
    template_name = 'director/create_director.html'

    def get_success_url(self):
        return reverse('film:director:director-list')


def director_delete(request, pk):
    try:
        director = get_object_or_404(Director, pk=pk)
        director.delete()
        messages.success(request, f'Successfully deleted director {director}')
        return redirect('film:director:director-list')
    except Exception as e:
        messages.error(request, f'Error to delete director {e}')
        return redirect('film:director:director-list')

film/views.py
from django.contrib import messages
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse
from django.views.generic import CreateView, UpdateView
from django_filters.views import FilterView
from film.filters import FilmFilter
from film.models import Movie


class FilmListView(FilterView):
    model = Movie
    template_name = 'film/films.html'
    paginate_by = 25
    filterset_class = FilmFilter
    context_object_name = 'films'

    def get_queryset(self):
        queryset = super().get_queryset().select_related('director').prefetch_related('actors')
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        paginator = Paginator(self.object_list, self.paginate_by)
        paginator._count = len(self.filterset.qs)
        page = self.request.GET.get('page')

        try:
            films = paginator.page(page)
        except PageNotAnInteger:
            films = paginator.page(1)
        except EmptyPage:
            films = paginator.page(paginator.num_pages)

        context['films'] = films
        return context


class FilmCreateView(CreateView):
    template_name = 'film/create_film.html'
    model = Movie
    fields = ['title', 'year', 'actors', 'director']

    def get_success_url(self):
        return reverse('film:list_view')


class FilmEditView(UpdateView):
    pk_url_kwarg = 'pk'
    template_name = 'film/edit_film.html'
    model = Movie
    fields = ['title', 'year', 'actors', 'director']

    def get_success_url(self):
        return reverse('film:list_view')


def film_delete(request, pk):
    try:
        film = get_object_or_404(Movie, pk=pk)
        film.delete()
        messages.success(request, f"{film.title} deleted successfully")
        return redirect('film:list_view')
    except Exception as e:
        messages.error(request, f'Error deleting film: {e}')
        return redirect('film:list_view')

templates/film/create_film.html
{% extends 'base.html' %}


{% block content %}
    <section class="create-film global-padding">
        <form action='' method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit"> Create Film</button>
            <a href="{% url 'film:list_view' %}">
                <button type="button">Cancel</button>
            </a>
        </form>
    </section>
{% endblock %}

templates/film/edit_film.html
{% extends 'base.html' %}

{% block content %}
    <section class="edit-film global-padding">
        <form method="post">{% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Update</button>
            <a href="{% url 'film:list_view' %}">
                <button type="button">Cancel</button>
            </a>
        </form>
    </section>
{% endblock %}

templates/film/films.html
{% extends 'base.html' %}

{% block content %}
    <section class="films-section global-padding">
        {% include 'inc/_filter_form.html' %}



        <div class="film-card">
            {% for film in films %}
                <div class="film-info">
                    <div class="film-text">
                        <p class="film-title">Film: {{ film.title }}</p>
                        <p class="film-year">Year: {{ film.year }}</p>
                        <p class="film-director">Director: {{ film.director }}</p>
                        <ul class="actors-list">
                            <p>Actors:</p>
                            {% for actor in film.actors.all %}
                                <li class="actor">
                                    <span>{{ actor.name }}</span>
                                </li>
                            {% endfor %}
                        </ul>
                    </div>
                    <div class="film-actions">
                        <a href="{% url 'film:delete_view' film.pk %}" class="delete-film-link">
                            <button class="delete-film-btn" type="submit">Delete Film</button>
                        </a>
                        <a href="{% url 'film:edit_view' film.pk %}" class="edit-film-link">
                            <button class="edit-film-btn" type="submit">Edit Film</button>
                        </a>
                    </div>
                </div>
            {% endfor %}
        </div>

        {% include 'inc/_paginator.html' %}
    </section>
{% endblock %}