api/urls.py
from django.urls import path
from .views import DirectorListCreateView, DirectorRetrieveUpdateDestroyView, api_overview
from .views import ActorListCreateView, ActorRetrieveUpdateDestroyView
from .views import FilmListCreateView, MovieRetrieveUpdateDestroyView

urlpatterns = [
    path('', api_overview, name='api-overview'),

    path('directors/', DirectorListCreateView.as_view(), name='director-list-create'),
    path('directors/<int:pk>/', DirectorRetrieveUpdateDestroyView.as_view(), name='director-detail'),

    path('actors/', ActorListCreateView.as_view(), name='actor-list-create'),
    path('actors/<int:pk>/', ActorRetrieveUpdateDestroyView.as_view(), name='actor-detail'),

    path('film/', FilmListCreateView.as_view(), name='film-list-create'),
    path('film/<int:pk>/', MovieRetrieveUpdateDestroyView.as_view(), name='film-detail'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('api-auth/', include('rest_framework.urls')),
                  path("__debug__/", include("debug_toolbar.urls")),
                  path('', include('film.urls')),
                  path('api/', include('api.urls')),

              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

film/urls.py
from django.urls import path, include
from film.views import FilmListView, FilmCreateView, FilmEditView, film_delete

app_name = 'film'

urlpatterns = [
    path('', FilmListView.as_view(), name='list_view'),
    path('create-film/', FilmCreateView.as_view(), name='create_view'),
    path('edit-film/<int:pk>/', FilmEditView.as_view(), name='edit_view'),
    path('delete-film/<int:pk>/', film_delete, name='delete_view'),

    path('', include('film.modules.actors.urls')),
    path('', include('film.modules.director.urls')),

]

film/models.py
from django.db import models


class Director(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ('name',)


class Actor(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ('name',)


class Movie(models.Model):
    title = models.CharField(max_length=100)
    year = models.IntegerField()
    director = models.ForeignKey(Director, on_delete=models.CASCADE)
    actors = models.ManyToManyField(Actor)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ('-year',)

templates/inc/_filter_form.html
<form class="filter-form" method="get">
    <div class="form-group">
        <label for="id_title">Назва:</label>
        {{ filter.form.title }}
    </div>

    <div class="form-group">
        <label for="id_year">Рік:</label>
        <div class="custom-select">
            {{ filter.form.year }}
        </div>
    </div>

    <div class="form-group">
        <label for="id_director">Режисер:</label>
        {{ filter.form.director }}
    </div>

    <div class="form-group">
        <label for="id_actors">Актори:</label>
        {{ filter.form.actors }}
    </div>

    <button type="submit" class="btn btn-primary">Apply filters</button>


    <a href="{% url 'film:create_view' %}">
        <button type="button">Create Film</button>
    </a>

</form>

templates/inc/_messages.html
<div class="messages">
    {% for message in messages %}
        <div class="message {% if message.tags %}{{ message.tags }}{% endif %}">
            {{ message }}
            <span class="close" onclick="this.parentElement.style.display='none'">&times;</span>
        </div>
    {% endfor %}
</div>

<style>
    .messages {
        position: fixed;
        top: 20px;
        right: 20px;
        max-width: 300px;
        width: 100%;
        z-index: 9999;
    }

    .message {
        display: flex;
        justify-content: space-between;
        align-items: center;
        padding: 15px;
        margin-bottom: 15px;
        border-radius: 5px;
        box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
    }

    .error {
        background-color: #D32F2F;
        color: #fff;
    }

    .success {
        background-color: #43A047;
        color: #fff;
    }

    .warning {
        background-color: #FFA000;
        color: #fff;
    }

    .info {
        background-color: #1976D2;
        color: #fff;
    }

    .close {
        cursor: pointer;
        font-size: 18px;
        font-weight: bold;
    }
</style>

templates/inc/_nav.html
	<nav class="main-nav">
        <a href="{% url 'film:list_view' %}">Films</a>
        <a href="{% url 'film:actors:actors-list' %}">Actors</a>
        <a href="{% url 'film:director:director-list' %}">Directors</a>
    </nav>

templates/inc/_paginator.html
<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?{% if request.GET.title %}title={{ request.GET.title }}&{% endif %}{% if request.GET.year %}year={{ request.GET.year }}&{% endif %}{% if request.GET.director %}director={{ request.GET.director }}&{% endif %}{% if request.GET.actors %}actors={{ request.GET.actors }}&{% endif %}{% if request.GET.name %}name={{ request.GET.name }}&{% endif %}page=1">&laquo;</a>
            <a href="?{% if request.GET.title %}title={{ request.GET.title }}&{% endif %}{% if request.GET.year %}year={{ request.GET.year }}&{% endif %}{% if request.GET.director %}director={{ request.GET.director }}&{% endif %}{% if request.GET.actors %}actors={{ request.GET.actors }}&{% endif %}{% if request.GET.name %}name={{ request.GET.name }}&{% endif %}page={{ page_obj.previous_page_number }}">&#8249;</a>
        {% else %}
            <span class="disabled">&laquo;</span>
            <span class="disabled">&#8249;</span>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?{% if request.GET.title %}title={{ request.GET.title }}&{% endif %}{% if request.GET.year %}year={{ request.GET.year }}&{% endif %}{% if request.GET.director %}director={{ request.GET.director }}&{% endif %}{% if request.GET.actors %}actors={{ request.GET.actors }}&{% endif %}{% if request.GET.name %}name={{ request.GET.name }}&{% endif %}page={{ page_obj.next_page_number }}">&#8250;</a>
            <a href="?{% if request.GET.title %}title={{ request.GET.title }}&{% endif %}{% if request.GET.year %}year={{ request.GET.year }}&{% endif %}{% if request.GET.director %}director={{ request.GET.director }}&{% endif %}{% if request.GET.actors %}actors={{ request.GET.actors }}&{% endif %}{% if request.GET.name %}name={{ request.GET.name }}&{% endif %}page={{ page_obj.paginator.num_pages }}">&raquo;</a>
        {% else %}
            <span class="disabled">&#8250;</span>
            <span class="disabled">&raquo;</span>
        {% endif %}
    </span>
</div>